project:
  type: website
  output-dir: docs

website:
  title: "I/O"
  favicon: "flamme_personnage.png"
  search: true
  navbar:
    logo: "disk.jpeg" 
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: posts.qmd
    right: 
    - icon: github
      href: https://github.com/IO-Thyr
    - icon: linkedin
      href: https://www.linkedin.com/in/tancrede-hayer/
    - icon: youtube
      href: https://www.youtube.com/@essience

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    mainfont: "roboto"
    fontsize: 16px